FROM node:18-alpine

WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY . .

EXPOSE 3000

RUN apk add --no-cache
ENV NODE_ENV=production \
    HEADWAY_MIN=3 \
    LAST_WINDOW_START=00:45 \
    SERVICE_END=01:15 \
    PGHOST=db \
    PGPORT=5432 \
    PGDATABASE=dernier_metro \
    PGUSER=dernier_metro \
    PGPASSWORD=dernier_metro

CMD ["node", "server.js"]


