services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.v1
    image: dernier-metro:v1
    environment:
      - PORT=3000
      - HEADWAY_MIN=3
      - LAST_WINDOW_START=00:45
      - SERVICE_END=01:15
      - DATABASE_URL=postgres://dernier_metro:dernier_metro@db:5432/dernier_metro
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=dernier_metro
      - POSTGRES_USER=dernier_metro
      - POSTGRES_PASSWORD=dernier_metro
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  swagger:
    image: swaggerapi/swagger-ui:latest
    environment:
      - URL=/openapi/openapi.yaml
    volumes:
      - ./openapi:/usr/share/nginx/html/openapi:ro
    ports:
      - "8080:8080"
    depends_on:
      - api

volumes:
  db_data:
